language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base qt59serialport desktop-file-utils
  - source /opt/qt*/bin/qt*-env.sh

script:
  - cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j$(nproc)
  - mkdir -p ./appdir/usr/bin
  # make DESTDIR=appdir -j$(nproc) install ; find appdir/ # Needs to be made work instead of the following lines
  - cp ESP_Flashing_Utility ./appdir/usr/bin # FIXME
  - mkdir -p ./appdir/usr/share/applications ; cp cuteesp.desktop ./appdir/usr/share/applications # FIXME
  - mkdir -p ./appdir/usr/share/icons/hicolor/scalable/apps ; touch ./appdir/usr/share/icons/hicolor/scalable/apps/cuteesp.svg # FIXME
  # Bundle esptool
  - wget -c "https://raw.githubusercontent.com/AppImage/pkg2appimage/master/pkg2appimage"
  - bash -ex pkg2appimage esptool
  - rm -rf esptool/esptool.AppDir/*.desktop esptool/esptool.AppDir/*.svg esptool/esptool.AppDir/usr/share/icons esptool/esptool.AppDir/usr/share/applications
  - cp -Rf esptool/esptool.AppDir/* appdir/
  - ( cd appdir ; wget -c "https://github.com/AppImage/AppImageKit/releases/download/11/AppRun-x86_64" -O AppRun ; chmod +x AppRun )
  # Remove files that are not absolutely needed
  - ( cd appdir/ ; find . -type f -or -type s | sort | uniq > ../ALLFILES ; diff --new-line-format="" --unchanged-line-format="" ../ALLFILES ../MANIFEST | xargs -r rm )
  - find appdir/ -type d -empty -delete
  # Make AppImage
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Cute*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
